tor:
    build: ./tor

browser:
    build: ./browser

    cap_add:
        - NET_ADMIN

    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:ro
        - /dev/snd:/dev/snd

    environment:
        - DISPLAY

    links:
        - tor
